### ISSUE TITLE
HNS Alert

### ISSUE THREAD

**Issue by Nathanwoodburn** [opensystm/handshake-micro-grants#16]
What have you built previously?
- [HNSHosting](https://hnshosting.au)
- [ShakeCities](https://shakecities.com)
- [Git Profile](https://github.com/nathanwoodburn)

Project summary
An open-source & self-hostable Handshake Alert System. This system provides email notifications for domain name expiries, changes to onchain domain records, and HTTPS certificate expirations. The project aims to provide peace of mind for users with control over their data, ensuring the security and continuous operation of their domain.

Features:
- Email notifications by default
- Bulk import of domains from NB or bob wallet
- Other notification options (possibly push via app, via discord webhook or any webhook)
- Per domain or global notifications options (eg. opt out of SSL notifications)

Completion requirements:
- Basic functionality including
   - Domain Expiry email notifications
   - HTTPS expiry email notifications
   - Bulk import of domains

- Functional easy to deploy selfhostable site
- A hosted site with free public access

The initial version will be completed in 2-3 weeks with a fully fledged version released later as the community provides feature requests.

You can contact me at handshake @ nathan.woodburn.au

**Comment by handshake-enthusiast** [comment]
Great idea!  

>Other notification options (possibly push via app, via discord webhook or any webhook)  

A Telegram bot notification would be good to have too.

**Comment by Nathanwoodburn** [comment]
> Great idea!
> 
> > Other notification options (possibly push via app, via discord webhook or any webhook)
> 
> A Telegram bot notification would be good to have too.

Does telegram offer an easy way for users to create a bot? I haven't ever had a look into it as I hardly use it

**Comment by handshake-enthusiast** [comment]
>Does telegram offer an easy way for users to create a bot? I haven't ever had a look into it as I hardly use it

Yes, it's relatively easy for technical people to create a bot. For me a simple trigger of https://core.telegram.org/bots/api#sendmessage would be enough. A technical user could fill in chat_id, text and bot_token.
