### ISSUE TITLE
hns.directory

### ISSUE THREAD

**Issue by ghost** [opensystm/handshake-micro-grants#6]
# Introduction

Hello, my name is Ryan. I'm new to Handshake.

# hns.directory

I will be building a platform that gives new users of Handshake an easy way to find resources. 

It will be similar to [privacyguides.org](https://www.privacyguides.org/en/tools/) where you can select a category and it will display websites associated with the selection. 

Websites hosted with handshake domains will be given priority and will be more prominent to end users, though websites associated with handshake using icann domains will also be included.

Website owners can submit their sites as well as request changes to website descriptions and categories through a submission form, email, or git issue. 

Redirects for ease of use:
https://hns.directory/ --> https://dir.ectory/
https://shakedirectory/ --> https://dir.ectory/
https://shakespace/ --> https://dir.ectory/

# Completion Criteria

1. Develop an appealing landing page that immediately shows the utility of dir.ectory
2. Create simple documentation describing how to add and edit websites
3. Establish at least 10 categories for which websites will be organized
4. Add a mimimum of 25 Handshake websites with descriptions of what they offer
5. Working submission page for users to add sites (initially just emailed to be added manually)
6. Ensure the user experience is elegent for both mobile and desktop enviornments
7. Launch application at https://dir.ectory/

# Timeline

Week 1
- Create landing page and user interface components (header, footer, etc)
- Choose categories and find icons that match category
- Establish a list of Handshake hosted websites
- Write short descriptions of what each website offers

Week 2
- Add documentation for submiting new sites
- Create about page explaining the project
- Push to production environment

**Comment by ryanmmoon** [comment]
The Handshake Dir.ectory is live at https://dir.ectory/. Find websites using or supporting Handshake and submit your own sites. Share https://hns.directory/ to help onboard new users.

**Comment by handshake-enthusiast** [comment]
Great to have this up-to-date dir.ectory. Especially for new comers in my view. I like it!
